### ISSUE TITLE
Question about using stream.source

### ISSUE THREAD

**Issue by austinfrey** [dominictarr/pull-net#4]
I just wanted to see if this was a legitimate server setup. The example for the module is setup as an echo server, but what if I just want to request a file and stream it back to the client? Do I need to use the `stream.source` function on the server side? The code below seems to work how I'd like it to, but just wanted to make sure I wasn't missing anything.

```
/* server.js */
const createServer = require('pull-net/server')
const pull = require('pull-stream')
const file = require('pull-file')
const { take } = pull
const path = require('path')

const inputFile = path.resolve(__dirname, './path/to/file')

createServer( function (
    stream
){
    pull(
        file(inputFile),
        take(100),
        stream.sink
    )
}).listen(9999, '127.0.0.1')
```
Is it OK to not use `stream.source` if I don't need to stream any data to the server? thanks in advance!

**Comment by dominictarr** [comment]
no, that is fine!

**Comment by austinfrey** [comment]
Thanks for the feedback!
